"""
Script to generate pixel-art sprites for FruityFocus.
Creates clean, authentic, transparent PNG frames for:
- Idle (4 frames)
- Walk (4 frames)
- Focus (4 frames)
- Break (4 frames)
- Celebrate (4 frames)
And a consolidated spritesheet.
"""
from PIL import Image
import os

PALETTE = {
    '.': (0, 0, 0, 0),             # Transparent
    'X': (42, 23, 8, 255),          # Outline
    'B': (255, 183, 3, 255),        # Body Base (vibrant mango yellow)
    'H': (255, 225, 102, 255),      # Body Highlight
    'S': (247, 127, 0, 255),        # Body Shadow (warm orange)
    'D': (214, 40, 40, 255),        # Body Deep Shadow
    'L': (42, 157, 143, 255),       # Leaf Main Green
    'K': (129, 199, 132, 255),      # Leaf Highlight
    'J': (27, 94, 32, 255),         # Leaf Shadow / Outline
    'T': (93, 64, 55, 255),         # Stem
    'C': (255, 112, 166, 255),      # Cheek Blush Pink
    'E': (26, 26, 26, 255),         # Eye Pupil
    'W': (255, 255, 255, 255),      # Eye Shine / Specular
    'M': (59, 28, 10, 255),         # Mouth
    'F': (247, 127, 0, 255),        # Foot/Hand
    'P': (33, 150, 243, 255),       # Sweat drop
    'p': (187, 222, 251, 255),      # Sweat highlight
    'Z': (100, 181, 246, 255),      # Sleep Zzz
    '1': (255, 64, 129, 255),       # Confetti Pink
    '2': (255, 215, 0, 255),        # Confetti Yellow
    '3': (0, 229, 255, 255),        # Confetti Cyan
    '4': (105, 240, 174, 255),      # Confetti Green
}

def grid_to_image(grid_str):
    lines = [line.strip() for line in grid_str.strip().split('\n') if line.strip()]
    height = len(lines)
    width = len(lines[0])
    img = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    pixels = img.load()
    for y, line in enumerate(lines):
        for x, char in enumerate(line):
            color = PALETTE.get(char, (0, 0, 0, 0))
            pixels[x, y] = color
    return img

# 32x32 frames
# IDLE 0: Normal standing, eyes open
IDLE_0 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEWBBSEWSSDX.........
.......XHHHBEWBBSSEWSDX.........
.......XHHBBEEEBSSEEEDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDX........
.......XHHBBBBBBBMBBSSDX........
........XHBBBBBBBBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
................................
"""

# IDLE 1: Slight breath (up 1 pixel, subtle highlight shift)
IDLE_1 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEWBBSEWSSDX.........
.......XHHHBEWBBSSEWSDX.........
.......XHHBBEEEBSSEEEDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDX........
.......XHHBBBBBBBMBBSSDX........
........XHBBBBBBBBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
................................
................................
"""

# IDLE 2: Blinking (eyes cute curved closed lines)
IDLE_2 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEBBSSEBSDXX.........
.......XHHBBEEBSSEEEEDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDX........
.......XHHBBBBBBBMBBSSDX........
........XHBBBBBBBBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
................................
"""

IDLE_3 = IDLE_0

# WALK 0: Left foot step forward, right back
WALK_0 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEWBBSEWSSDX.........
.......XHHHBEWBBSSEWSDX.........
.......XHHBBEEEBSSEEEDX.........
.......XHHBCEECBMCEECDXX........
......XFHHBBBBBMXMBBSSDXX.......
......XFHHBBBBBBBMBBSSDXF.......
.......XXHBBBBBBBBBBSSXFFX......
........XHBBBBBBBBBBSSX.XX......
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
.........XFFX....XFFX...........
.........XFFX.....XX............
..........XX....................
................................
................................
................................
................................
"""

WALK_1 = IDLE_0

# WALK 2: Right foot forward, left back
WALK_2 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEWBBSEWSSDX.........
.......XHHHBEWBBSSEWSDX.........
.......XHHBBEEEBSSEEEDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDXF.......
......XFHHBBBBBBBMBBSSDXX.......
......XFXHBBBBBBBBBBSSX.........
.......XXHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX....XFFX.........
............XX.....XFFX.........
....................XX..........
................................
................................
................................
................................
"""

WALK_3 = IDLE_1

# FOCUS 0: Determined eyebrows, sweat drop appearing
FOCUS_0 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XpPHHBBBBBBSSSSDX........
.......XPPHEWBBSEWSSSDX.........
.......XHHHEEBBSSEEESDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDX........
.......XHHBBBBBBMXMBSSDX........
.......XHHBBBBBBBBMBSSDX........
........XHBBBBBBBBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
................................
"""

# FOCUS 1: Sweat drop trickles slightly, focused glare
FOCUS_1 = """
................................
................TT..............
...............TJKK.............
...............JKKLLX...........
..............XLLLLLX...........
............XXXXLLLX............
...........XHHHHXXXX............
..........XHHHHHBBSX............
.........XHHHHHBBBSSX...........
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XpPHHBBBBBSSSSDX.........
.......XPPPHBBBBBBSSSSDX........
.......XXPHEWBBSEWSSSDX.........
.......XHHHEEBBSSEEESDX.........
.......XHHBCEECBMCEECDXX........
.......XHHBBBBBMXMBBSSDX........
.......XHHBBBBBBMXMBSSDX........
.......XHHBBBBBBBBMBSSDX........
........XHBBBBBBBBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
................................
"""

FOCUS_2 = FOCUS_0
FOCUS_3 = FOCUS_1

# BREAK 0: Lying down / sleeping peacefully, small z
BREAK_0 = """
................................
................................
................................
................................
................................
................................
.....................ZZZ........
....................X..Z........
......................Z.........
.....................ZZZ........
..............TT................
.............TJKK...............
.............JKKLLX.............
............XLLLLLX.............
..........XXXXLLLX..............
.........XHHHHXXXX..............
........XHHHHHBBSXXXXXXXXX......
.......XHHHHHBBBSSBBBBBBBDX.....
......XHHHHHBBBSSSSBBBBBBDX.....
......XHHHHBBBBSSSSBBBBBBDX.....
.....XHHHHBBBBBEBBSSEBSSSDX.....
.....XHHHBBBBBBCEECBMCEECDX.....
.....XHHHBBBBBBBBBMXMBBBBDX.....
.....XHHHBBBBBBBBBBBBBBBBDX.....
......XHHBBBBBBBBBBBBBBBBDX.....
......XHBBBBBBBBBBBBBBBBBDX.....
.......XBBBBBBBBBBBBBBBBBDX.....
........XXXXXXXXXFFXXXFFXX......
................XFFX.XFFX.......
.................XX...XX........
................................
................................
"""

# BREAK 1: Sleeping, medium Z floating higher
BREAK_1 = """
................................
................................
...................ZZZZ.........
..................X...Z.........
.....................Z..........
....................ZZZZ........
................................
................................
................................
................................
..............TT................
.............TJKK...............
.............JKKLLX.............
............XLLLLLX.............
..........XXXXLLLX..............
.........XHHHHXXXX..............
........XHHHHHBBSXXXXXXXXX......
.......XHHHHHBBBSSBBBBBBBDX.....
......XHHHHHBBBSSSSBBBBBBDX.....
......XHHHHBBBBSSSSBBBBBBDX.....
.....XHHHHBBBBBEBBSSEBSSSDX.....
.....XHHHBBBBBBCEECBMCEECDX.....
.....XHHHBBBBBBBBBMXMBBBBDX.....
.....XHHHBBBBBBBBBBBBBBBBDX.....
......XHHBBBBBBBBBBBBBBBBDX.....
......XHBBBBBBBBBBBBBBBBBDX.....
.......XBBBBBBBBBBBBBBBBBDX.....
........XXXXXXXXXFFXXXFFXX......
................XFFX.XFFX.......
.................XX...XX........
................................
................................
"""

BREAK_2 = BREAK_0
BREAK_3 = BREAK_1

# CELEBRATE 0: Jump up with hands raised, sparkles
CELEBRATE_0 = """
....2....................1......
...222..................111.....
....2....................1......
................TT..............
...............TJKK.............
...............JKKLLX...........
...XFFX.......XLLLLLX.......XFFX
...XFFX.....XXXXLLLX........XFFX
....XX.....XHHHHXXXX.........XX.
...XFFX...XHHHHHBBSX........XFFX
....XX...XHHHHHBBBSSX........XX.
........XHHHHHBBBSSSSX..........
........XHHHHBBBBSSSSX..........
.......XHHHHBBBBBSSSSDX.........
.......XHHHBBBBBBSSSSDX.........
.......XHHHBEWBBSEWSSDX...3.....
.......XHHHBEWBBSSEWSDX..333....
.......XHHBBEEEBSSEEEDX...3.....
.......XHHBCEECBMCEECDXX........
.......XHHBBBBMMMMBBSSDX........
.......XHHBBBBWMMWBBSSDX........
........XHBBBBBMMBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XBBBBBBBSX...........
............XXXXXXXX............
...........XFFX..XFFX...........
............XX....XX............
................................
................................
................................
"""

# CELEBRATE 1: Full peak jump, confetti exploding!
CELEBRATE_1 = """
...3.....2..................4...
..333...222.......1........444..
...3.....2.......111........4...
..................1.............
................TT..............
...............TJKK.............
...XFFX.......JKKLLX........XFFX
...XFFX......XLLLLLX........XFFX
....XX.....XXXXLLLX..........XX.
....XFFX..XHHHHXXXX.........XFFX
.....XX..XHHHHHBBSX..........XX.
........XHHHHHBBBSSX............
........XHHHHHBBBSSSSX....2.....
.......XHHHHBBBBSSSSX....222....
.......XHHHHBBBBBSSSSDX...2.....
.......XHHHBEWBBSEWSSDX.........
.......XHHHBEWBBSSEWSDX.........
.......XHHBBEEEBSSEEEDX.........
.......XHHBCEECBMCEECDXX........
...1...XHHBBBBMMMMBBSSDX........
..111..XHHBBBBWMMWBBSSDX........
...1....XHBBBBBMMBBBSSX.........
........XHBBBBBBBBBBSSX.........
.........XBBBBBBBBBSDX..........
..........XBBBBBBBBSX...........
...........XXXXXXXXX............
............XFFXXFFX............
............XFFXXFFX............
.............XX..XX.............
................................
................................
................................
"""

CELEBRATE_2 = CELEBRATE_0
CELEBRATE_3 = CELEBRATE_1

ANIMATIONS = {
    'idle': [IDLE_0, IDLE_1, IDLE_2, IDLE_3],
    'walk': [WALK_0, WALK_1, WALK_2, WALK_3],
    'focus': [FOCUS_0, FOCUS_1, FOCUS_2, FOCUS_3],
    'break': [BREAK_0, BREAK_1, BREAK_2, BREAK_3],
    'celebrate': [CELEBRATE_0, CELEBRATE_1, CELEBRATE_2, CELEBRATE_3],
}

def generate_all(output_dir):
    os.makedirs(output_dir, exist_ok=True)
    all_frames = {}
    scale_factor = 3  # 32x32 -> 96x96 default render size
    
    for state_name, frames in ANIMATIONS.items():
        all_frames[state_name] = []
        for idx, grid_str in enumerate(frames):
            img_32 = grid_to_image(grid_str)
            filename_32 = f"{state_name}_{idx}.png"
            path_32 = os.path.join(output_dir, filename_32)
            img_32.save(path_32)
            
            # Scaled version (nearest neighbor)
            img_scaled = img_32.resize((32 * scale_factor, 32 * scale_factor), Image.Resampling.NEAREST)
            filename_scaled = f"{state_name}_{idx}_x{scale_factor}.png"
            path_scaled = os.path.join(output_dir, filename_scaled)
            img_scaled.save(path_scaled)
            all_frames[state_name].append(img_32)
            
    # Also generate a consolidated SpriteSheet (5 rows, 4 columns)
    cols = 4
    rows = len(ANIMATIONS)
    sheet_w = cols * 32
    sheet_h = rows * 32
    spritesheet = Image.new('RGBA', (sheet_w, sheet_h), (0, 0, 0, 0))
    
    for row, (state_name, frame_imgs) in enumerate(all_frames.items()):
        for col, img in enumerate(frame_imgs):
            spritesheet.paste(img, (col * 32, row * 32))
            
    sheet_path = os.path.join(output_dir, "spritesheet_32.png")
    spritesheet.save(sheet_path)
    
    sheet_scaled = spritesheet.resize((sheet_w * scale_factor, sheet_h * scale_factor), Image.Resampling.NEAREST)
    sheet_scaled_path = os.path.join(output_dir, "spritesheet.png")
    sheet_scaled.save(sheet_scaled_path)
    
    print(f"Successfully generated all sprite frames and spritesheet in {output_dir}")

if __name__ == "__main__":
    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "assets", "sprites"))
    generate_all(out)
